### ISSUE TITLE
New Project does not sync

### ISSUE THREAD

**Issue by Ibrahim-Halil-Kuray** [dribdat/dribdat#345] opened 2023-04-17 13:14 UTC
I created a project from my github repo after saving I got an error message "You are not allowed to sync"

**Comment by loleg** [comment] 2023-04-28 23:27
Thanks for the bug report, and welcome to the project! It would be great to have a screenshot and a link to the problematic repo to try to debug this.

I will try to reproduce this. It might be a permissions issue. Challenge owners should be allowed to sync even without Joining a new project.

**Comment by loleg** [comment] 2023-05-09 21:04
Closing since I cannot reproduce the bug. Please make sure that your repository has a README.

**Closed as completed by loleg** 2023-05-09 21:04 UTC
Labels: bug
